### ISSUE TITLE
🐛 ⌨ One Letter at a Time

### ISSUE THREAD

**Issue by shnizzedy** [akeshavan/mindlogger-app-admin-v2#12]
In the `Editing Screens` view, in the `List Options` section, in the `Text` column (where the screenshot below says `option 0`), the interface currently kicks the user out of the text field after a keystroke. 

![List options: Text: option 0](https://user-images.githubusercontent.com/5974438/53439593-5c896600-39d0-11e9-8801-e96a52ae2553.png)

**Comment by akeshavan** [comment]
the weird thing about this bug is that I can't get it to happen when running locally!!

**Comment by shnizzedy** [comment]
But you do see this behavior at [mindlogger.anisha.:pizza:](https://mindlogger.anisha.pizza), right? Weird!

**Comment by akeshavan** [comment]
fixed with https://github.com/akeshavan/mindlogger-app-admin-v2/commit/1d4711ad3a87589d5c2c884bc4740b1104fb78f6 no idea why it was working locally but oh well! Now we only hit the server when the input is deselected
